-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 17:17:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mundo_digital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundo_digital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundo_digital` DEFAULT CHARACTER SET utf8 ;
USE `mundo_digital` ;

-- -----------------------------------------------------
-- Table `mundo_digital`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo_digital`.`categoria` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nome` VARCHAR(45) NOT NULL,
  `cat_slug` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundo_digital`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo_digital`.`produtos` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nome` VARCHAR(45) NOT NULL,
  `pro_categoria` INT NOT NULL,
  `pro_descricao` TEXT(255) NOT NULL,
  `pro_peso` DOUBLE NOT NULL,
  `pro_valor` DOUBLE NOT NULL,
  `pro_altura` INT NOT NULL,
  `pro_largura` INT NOT NULL,
  `pro_comprimento` INT NOT NULL,
  `pro_img` VARCHAR(200) NOT NULL,
  `pro_slug` VARCHAR(100) NOT NULL,
  `pro_estoque` INT NOT NULL,
  `pro_modelo` VARCHAR(45) NOT NULL,
  `pro_referencia` VARCHAR(45) NOT NULL,
  `pro_fabricante` VARCHAR(45) NOT NULL,
  `pro_ativo` CHAR NOT NULL,
  `pro_frete_free` VARCHAR(100),
  PRIMARY KEY (`pro_id`),
  INDEX `fk_produtos_categoria_idx` (`pro_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categoria`
    FOREIGN KEY (`pro_categoria`)
    REFERENCES `mundo_digital`.`categoria` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
